# Generated by Django 5.2.5 on 2025-08-09 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("rust", "Rust"),
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("go", "Go"),
                            ("cpp", "C++"),
                        ],
                        default="rust",
                        max_length=20,
                    ),
                ),
                ("input_data", models.TextField(blank=True)),
                ("output", models.TextField(blank=True)),
                ("error_output", models.TextField(blank=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("language", models.CharField(max_length=20)),
                ("template_code", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("language", "is_default")},
            },
        ),
    ]
